name 'logstash'
maintainer 'Henry Akinola'
maintainer_email 'henryakinola59@gmail.com'
licence 'elasticsearch'
description  'Installs logstash and applies required configurations'
long_description 'Install logstash, updates the configuration with what is found in the templates diretcory'
version '0.0.1'

supports 'centos8'
recipe 'logstash::logstash', 'Installs latest logstash version (currently:7.6)'
