name 'kibana'
maintainer 'Henry Akinola'
maintainer_email 'henryakinola59@gmail.com'
licence 'elasticsearch'
description  'Installs Kibana and applies required configurations'
long_description 'Install Kibana, updates the configuration with what is found in the templates diretcory'
version '0.1.4'

supports 'centos8'
recipe 'kibana::kibana_build', 'Installs latest Kibana version (currently:7.6)'
recipe 'kibana::nginx_setup', 'Installs and configures nginx on server'
